### ISSUE TITLE
Documentation discrepancies

### ISSUE THREAD

**Issue by craibuc** [akosma/eBook-Template#4]
There are some minor differences in the installation instructions between https://github.com/akosmasoftware/eBook-Template and http://akosmasoftware.github.io/eBook-Template.  Which one is accurate?

http://akosmasoftware.github.io/eBook-Template mentions installing MacTex, which seems to be a requirement (I needed to install it, then reboot before I could `brew install dblatex`).

In addition to the differences, the installation instructions omit steps.  For example, your Makefile references `docbook-xsl`, but `brew install docbook-xsl` isn't included in the instructions.
I can certainly make the changes to the project's README.md, then send you a pull request, but I wanted to make sure that I'm not misunderstanding something.

**Comment by akosma** [comment]
The new version is out, and it makes the installation much simpler.
